import Head from "next/head";
import { Montserrat } from "@next/font/google";
import { useEffect, useState } from "react";
import { useTheme } from "next-themes";
const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
});
let plans = [
  {
    name: "Basic",
    price: {
      monthly: 19.99,
      annually: 199.99,
    },
    features: ["500 GB Storage", "2 Users Allowed", "Send up to 3 GB"],
  },
  {
    name: "Professional",
    price: {
      monthly: 24.99,
      annually: 249.99,
    },
    features: ["1 TB Storage", "5 Users Allowed", "Send up to 10 GB"],
  },
  {
    name: "Master",
    price: {
      monthly: 39.99,
      annually: 399.99,
    },
    features: ["2 TB Storage", "10 Users Allowed", "Send up to 20 GB"],
  },
];
export default function Home() {
  const [checked, setChecked] = useState(false);
  const { theme, setTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Pricing Component - coded by joehsn</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={montserrat.className}>
        <div className="container">
          <header>
            <h1>Our Pricing</h1>
            <div className="toggler">
              <p>Monthly</p>
              <label>
                <input
                  type="checkbox"
                  className="sr-only peer"
                  checked={checked}
                  onChange={() => {
                    setChecked(!checked);
                  }}
                />
                <div className="peer peer-checked:after:translate-x-full peer-checked:after:border-white peer-checked:bg-FLPG"></div>
              </label>
              <p>Annually</p>
            </div>
          </header>
          <div className="plans">
            {plans.map((plan, index) => {
              const { name, price, features } = plan;
              return (
                <div key={index} className="plan">
                  <h2>{name}</h2>
                  <p className="price">
                    ${!checked ? price.monthly : price.annually}
                  </p>
                  <ul className="features">
                    {features.map((feature, index) => (
                      <li key={index}>{feature}</li>
                    ))}
                  </ul>
                  <a className="btn" href={`#${name.toLowerCase()}-plan`}>
                    Learn More
                  </a>
                </div>
              );
            })}
          </div>
        </div>
      </main>
      <footer className="attribution">
        <div>
          Coded with ❤️ by{" "}
          <a href="https://linktr.ee/joehsn" target="_blank" rel="noreferrer">
            @joehsn
          </a>
          .
        </div>
        <select value={theme} onChange={(e) => setTheme(e.target.value)}>
          <option value="system">System</option>
          <option value="dark">Dark</option>
          <option value="light">Light</option>
        </select>
      </footer>
    </>
  );
}
